// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for creating a TagKey.
public struct CreateTagKeyRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The TagKey to be created. Only fields `short_name`,
  /// `description`, and `parent` are considered during the creation request.
  public var tagKey: TagKey?

  /// Optional. Set to true to perform validations necessary for creating the
  /// resource, but not actually perform the action.
  public var validateOnly: Swift.Bool

  /// Initialize a new instance of `CreateTagKeyRequest`.
  public init(
    tagKey: TagKey? = nil,
    validateOnly: Swift.Bool = Swift.Bool(),
  ) {
    self.tagKey = tagKey
    self.validateOnly = validateOnly
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.CreateTagKeyRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
