// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A status object which is used as the `metadata` field for the Operation
/// returned by CreateProject. It provides insight for when significant phases of
/// Project creation have completed.
public struct CreateProjectMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Creation time of the project creation workflow.
  public var createTime: GoogleCloudWkt.Timestamp?

  /// True if the project can be retrieved using `GetProject`. No other
  /// operations on the project are guaranteed to work until the project creation
  /// is complete.
  public var gettable: Swift.Bool

  /// True if the project creation process is complete.
  public var ready: Swift.Bool

  /// Initialize a new instance of `CreateProjectMetadata`.
  public init(
    createTime: GoogleCloudWkt.Timestamp? = nil,
    gettable: Swift.Bool = Swift.Bool(),
    ready: Swift.Bool = Swift.Bool(),
  ) {
    self.createTime = createTime
    self.gettable = gettable
    self.ready = ready
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.CreateProjectMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
