// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message to delete a TagHold.
public struct DeleteTagHoldRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the TagHold to delete. Must be of the form:
  /// `tagValues/{tag-value-id}/tagHolds/{tag-hold-id}`.
  public var name: Swift.String

  /// Optional. Set to true to perform the validations necessary for deleting the
  /// resource, but not actually perform the action.
  public var validateOnly: Swift.Bool

  /// Initialize a new instance of `DeleteTagHoldRequest`.
  public init(
    name: Swift.String = Swift.String(),
    validateOnly: Swift.Bool = Swift.Bool(),
  ) {
    self.name = name
    self.validateOnly = validateOnly
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.DeleteTagHoldRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
