// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for deleting a TagValue.
public struct DeleteTagValueRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Resource name for TagValue to be deleted in the format
  /// tagValues/456.
  public var name: Swift.String

  /// Optional. Set as true to perform the validations necessary for deletion,
  /// but not actually perform the action.
  public var validateOnly: Swift.Bool

  /// Optional. The etag known to the client for the expected state of the
  /// TagValue. This is to be used for optimistic concurrency.
  public var etag: Swift.String

  /// Initialize a new instance of `DeleteTagValueRequest`.
  public init(
    name: Swift.String = Swift.String(),
    validateOnly: Swift.Bool = Swift.Bool(),
    etag: Swift.String = Swift.String(),
  ) {
    self.name = name
    self.validateOnly = validateOnly
    self.etag = etag
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.DeleteTagValueRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
