// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An EffectiveTag represents a tag that applies to a resource during policy
/// evaluation. Tags can be either directly bound to a resource or inherited from
/// its ancestor. EffectiveTag contains the name and
/// namespaced_name of the tag value and tag key, with additional fields of
/// `inherited` to indicate the inheritance status of the effective tag.
public struct EffectiveTag: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Resource name for TagValue in the format `tagValues/456`.
  public var tagValue: Swift.String = Swift.String()

  /// The namespaced name of the TagValue. Can be in the form
  /// `{organization_id}/{tag_key_short_name}/{tag_value_short_name}` or
  /// `{project_id}/{tag_key_short_name}/{tag_value_short_name}` or
  /// `{project_number}/{tag_key_short_name}/{tag_value_short_name}`.
  public var namespacedTagValue: Swift.String = Swift.String()

  /// The name of the TagKey, in the format `tagKeys/{id}`, such as
  /// `tagKeys/123`.
  public var tagKey: Swift.String = Swift.String()

  /// The namespaced name of the TagKey. Can be in the form
  /// `{organization_id}/{tag_key_short_name}` or
  /// `{project_id}/{tag_key_short_name}` or
  /// `{project_number}/{tag_key_short_name}`.
  public var namespacedTagKey: Swift.String = Swift.String()

  /// The parent name of the tag key.
  /// Must be in the format `organizations/{organization_id}` or
  /// `projects/{project_number}`
  public var tagKeyParentName: Swift.String = Swift.String()

  /// Indicates the inheritance status of a tag value
  /// attached to the given resource. If the tag value is inherited from one of
  /// the resource's ancestors, inherited will be true. If false, then the tag
  /// value is directly attached to the resource, inherited will be false.
  public var inherited: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `EffectiveTag`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EffectiveTag().with { $0.tagValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.EffectiveTag"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
