// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for getting a TagValue by its namespaced name.
public struct GetNamespacedTagValueRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. A namespaced tag value name in the following format:
  ///
  ///   `{parentId}/{tagKeyShort}/{tagValueShort}`
  ///
  /// Examples:
  /// - `42/foo/abc` for a value with short name "abc" under the key with short
  ///   name "foo" under the organization with ID 42
  /// - `r2-d2/bar/xyz` for a value with short name "xyz" under the key with
  ///    short name "bar" under the project with ID "r2-d2"
  public var name: Swift.String

  /// Initialize a new instance of `GetNamespacedTagValueRequest`.
  public init(
    name: Swift.String = Swift.String(),
  ) {
    self.name = name
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.GetNamespacedTagValueRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
