// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for listing the TagHolds under a TagValue.
public struct ListTagHoldsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the parent TagValue. Must be of the form:
  /// `tagValues/{tag-value-id}`.
  public var parent: Swift.String

  /// Optional. The maximum number of TagHolds to return in the response. The
  /// server allows a maximum of 300 TagHolds to return. If unspecified, the
  /// server will use 100 as the default.
  public var pageSize: Swift.Int32

  /// Optional. A pagination token returned from a previous call to
  /// `ListTagHolds` that indicates where this listing should continue from.
  public var pageToken: Swift.String

  /// Optional. Criteria used to select a subset of TagHolds parented by the
  /// TagValue to return. This field follows the syntax defined by aip.dev/160;
  /// the `holder` and `origin` fields are supported for filtering. Currently
  /// only `AND` syntax is supported. Some example queries are:
  ///
  ///   * `holder =
  ///     //compute.googleapis.com/compute/projects/myproject/regions/us-east-1/instanceGroupManagers/instance-group`
  ///   * `origin = 35678234`
  ///   * `holder =
  ///     //compute.googleapis.com/compute/projects/myproject/regions/us-east-1/instanceGroupManagers/instance-group
  ///     AND origin = 35678234`
  public var filter: Swift.String

  /// Initialize a new instance of `ListTagHoldsRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    pageSize: Swift.Int32 = Swift.Int32(),
    pageToken: Swift.String = Swift.String(),
    filter: Swift.String = Swift.String(),
  ) {
    self.parent = parent
    self.pageSize = pageSize
    self.pageToken = pageToken
    self.filter = filter
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.ListTagHoldsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
