// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request message to ListEffectiveTags
public struct ListEffectiveTagsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The full resource name of a resource for which you want to list
  /// the effective tags. E.g.
  /// "//cloudresourcemanager.googleapis.com/projects/123"
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of effective tags to return in the response.
  /// The server allows a maximum of 300 effective tags to return in a single
  /// page. If unspecified, the server will use 100 as the default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A pagination token returned from a previous call to
  /// `ListEffectiveTags` that indicates from where this listing should continue.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListEffectiveTagsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEffectiveTagsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.ListEffectiveTagsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
