// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Metadata pertaining to the folder move process.
public struct MoveFolderMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The display name of the folder.
  public var displayName: Swift.String

  /// The resource name of the folder's parent.
  public var sourceParent: Swift.String

  /// The resource name of the folder or organization to move the folder to.
  public var destinationParent: Swift.String

  /// Initialize a new instance of `MoveFolderMetadata`.
  public init(
    displayName: Swift.String = Swift.String(),
    sourceParent: Swift.String = Swift.String(),
    destinationParent: Swift.String = Swift.String(),
  ) {
    self.displayName = displayName
    self.sourceParent = sourceParent
    self.destinationParent = destinationParent
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.MoveFolderMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
