// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The root node in the resource hierarchy to which a particular entity's
/// (a company, for example) resources belong.
public struct Organization: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the organization. This is the
  /// organization's relative path in the API. Its format is
  /// "organizations/[organization_id]". For example, "organizations/1234".
  public var name: Swift.String = Swift.String()

  /// Output only. A human-readable string that refers to the organization in the
  /// Google Cloud Console. This string is set by the server and cannot be
  /// changed. The string will be set to the primary domain (for example,
  /// "google.com") of the Google Workspace customer that owns the organization.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The organization's current lifecycle state.
  public var state: Organization.State = Organization.State()

  /// Output only. Timestamp when the Organization was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Timestamp when the Organization was last modified.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Timestamp when the Organization was requested for deletion.
  public var deleteTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. A checksum computed by the server based on the current value
  /// of the Organization resource. This may be sent on update and delete
  /// requests to ensure the client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// The owner of this organization. The owner should be specified on
  /// creation. Once set, it cannot be changed.
  ///
  /// The lifetime of the organization and all of its descendants are bound to
  /// the owner. If the owner is deleted, the organization and all its
  /// descendants will be deleted.
  public var owner: OwnerOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Organization`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Organization().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let directoryCustomerId = CodingKeys(stringValue: "directoryCustomerId")
    static let state = CodingKeys(stringValue: "state")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "directoryCustomerId",
      "state",
      "createTime",
      "updateTime",
      "deleteTime",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Organization.State.self, forKey: .state) {
      self.state = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }

    var owner: OwnerOneOf? = nil
    let ownerCheckAndSet = {
      if owner != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'owner'"))
      }
      owner = $0
    }
    if let directoryCustomerId = try container.decodeIfPresent(
      Swift.String.self, forKey: .directoryCustomerId)
    {
      try ownerCheckAndSet(.directoryCustomerId(directoryCustomerId))
    }
    self.owner = owner
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.etag, forKey: .etag)

    if let choice = self.owner {
      switch choice {
      case .directoryCustomerId(let value):
        try container.encode(value, forKey: .directoryCustomerId)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Organization lifecycle states.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// Unspecified state.  This is only useful for distinguishing unset values.
    case unspecified
    /// The normal and active state.
    case active
    /// The organization has been marked for deletion by the user.
    case deleteRequested
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .deleteRequested: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .deleteRequested: return "DELETE_REQUESTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "DELETE_REQUESTED": self = .deleteRequested
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .deleteRequested
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .deleteRequested: return try container.encode("DELETE_REQUESTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The owner of this organization. The owner should be specified on
  /// creation. Once set, it cannot be changed.
  ///
  /// The lifetime of the organization and all of its descendants are bound to
  /// the owner. If the owner is deleted, the organization and all its
  /// descendants will be deleted.
  public enum OwnerOneOf: Codable, Equatable, Sendable {
    /// Immutable. The G Suite / Workspace customer id used in the Directory API.
    case directoryCustomerId(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.Organization"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
