// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudWkt
import GoogleIamV1
import GoogleLongrunning
import Logging

/// Allows users to manage their organization resources.
///
/// @Snippet(path: "OrganizationsQuickstart")
public protocol Organizations {
  /// Fetches an organization resource identified by the specified resource name.
  ///
  /// @Snippet(path: "Organizations_GetOrganization")
  func getOrganization(request: GetOrganizationRequest) async throws
    -> GoogleCloudResourcemanagerV3.Organization

  /// Searches organization resources that are visible to the user and satisfy
  /// the specified filter. This method returns organizations in an unspecified
  /// order. New organizations do not necessarily appear at the end of the
  /// results, and may take a small amount of time to appear.
  ///
  /// Search will only return organizations on which the user has the permission
  /// `resourcemanager.organizations.get`
  ///
  /// @Snippet(path: "Organizations_SearchOrganizations")
  func searchOrganizations(request: SearchOrganizationsRequest) async throws
    -> GoogleCloudResourcemanagerV3.SearchOrganizationsResponse

  /// Searches organization resources that are visible to the user and satisfy
  /// the specified filter. This method returns organizations in an unspecified
  /// order. New organizations do not necessarily appear at the end of the
  /// results, and may take a small amount of time to appear.
  ///
  /// Search will only return organizations on which the user has the permission
  /// `resourcemanager.organizations.get`
  func searchOrganizations(
    byItem: SearchOrganizationsRequest
  ) throws -> any AsyncSequence<Organization, Swift.Error>

  /// Gets the access control policy for an organization resource. The policy may
  /// be empty if no such policy or resource exists. The `resource` field should
  /// be the organization's resource name, for example: "organizations/123".
  ///
  /// Authorization requires the IAM permission
  /// `resourcemanager.organizations.getIamPolicy` on the specified organization.
  ///
  /// @Snippet(path: "Organizations_GetIamPolicy")
  func getIamPolicy(request: GetIamPolicyRequest) async throws -> GoogleIamV1.Policy

  /// Sets the access control policy on an organization resource. Replaces any
  /// existing policy. The `resource` field should be the organization's resource
  /// name, for example: "organizations/123".
  ///
  /// Authorization requires the IAM permission
  /// `resourcemanager.organizations.setIamPolicy` on the specified organization.
  ///
  /// @Snippet(path: "Organizations_SetIamPolicy")
  func setIamPolicy(request: SetIamPolicyRequest) async throws -> GoogleIamV1.Policy

  /// Returns the permissions that a caller has on the specified organization.
  /// The `resource` field should be the organization's resource name,
  /// for example: "organizations/123".
  ///
  /// There are no permissions required for making this API call.
  ///
  /// @Snippet(path: "Organizations_TestIamPermissions")
  func testIamPermissions(request: TestIamPermissionsRequest) async throws
    -> GoogleIamV1.TestIamPermissionsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Organizations_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Fetches an organization resource identified by the specified resource name.
  ///
  /// @Snippet(path: "Organizations_GetOrganization")
  func getOrganization(
    request: GetOrganizationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourcemanagerV3.Organization

  /// Searches organization resources that are visible to the user and satisfy
  /// the specified filter. This method returns organizations in an unspecified
  /// order. New organizations do not necessarily appear at the end of the
  /// results, and may take a small amount of time to appear.
  ///
  /// Search will only return organizations on which the user has the permission
  /// `resourcemanager.organizations.get`
  ///
  /// @Snippet(path: "Organizations_SearchOrganizations")
  func searchOrganizations(
    request: SearchOrganizationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourcemanagerV3.SearchOrganizationsResponse

  /// Searches organization resources that are visible to the user and satisfy
  /// the specified filter. This method returns organizations in an unspecified
  /// order. New organizations do not necessarily appear at the end of the
  /// results, and may take a small amount of time to appear.
  ///
  /// Search will only return organizations on which the user has the permission
  /// `resourcemanager.organizations.get`
  func searchOrganizations(
    byItem: SearchOrganizationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Organization, Swift.Error>

  /// Gets the access control policy for an organization resource. The policy may
  /// be empty if no such policy or resource exists. The `resource` field should
  /// be the organization's resource name, for example: "organizations/123".
  ///
  /// Authorization requires the IAM permission
  /// `resourcemanager.organizations.getIamPolicy` on the specified organization.
  ///
  /// @Snippet(path: "Organizations_GetIamPolicy")
  func getIamPolicy(
    request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy

  /// Sets the access control policy on an organization resource. Replaces any
  /// existing policy. The `resource` field should be the organization's resource
  /// name, for example: "organizations/123".
  ///
  /// Authorization requires the IAM permission
  /// `resourcemanager.organizations.setIamPolicy` on the specified organization.
  ///
  /// @Snippet(path: "Organizations_SetIamPolicy")
  func setIamPolicy(
    request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy

  /// Returns the permissions that a caller has on the specified organization.
  /// The `resource` field should be the organization's resource name,
  /// for example: "organizations/123".
  ///
  /// There are no permissions required for making this API call.
  ///
  /// @Snippet(path: "Organizations_TestIamPermissions")
  func testIamPermissions(
    request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.TestIamPermissionsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Organizations_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation
}

extension Clients {
  /// The recommended implementation for ``Organizations``.
  public class OrganizationsClient: Organizations {
    let inner: any OrganizationsStub

    /// Creates a new `OrganizationsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any OrganizationsStub = try OrganizationsTransport(options)
      inner = OrganizationsRetry(inner, options: options)
      if let logger = options.logger {
        inner = OrganizationsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `Organizations.getOrganization`
    public func getOrganization(
      request: GetOrganizationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourcemanagerV3.Organization {
      try await self.inner.getOrganization(request: request, options: options)
    }

    /// See `Organizations.searchOrganizations`
    public func searchOrganizations(
      request: SearchOrganizationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourcemanagerV3.SearchOrganizationsResponse {
      try await self.inner.searchOrganizations(request: request, options: options)
    }

    /// Searches organization resources that are visible to the user and satisfy
    /// the specified filter. This method returns organizations in an unspecified
    /// order. New organizations do not necessarily appear at the end of the
    /// results, and may take a small amount of time to appear.
    ///
    /// Search will only return organizations on which the user has the permission
    /// `resourcemanager.organizations.get`
    public func searchOrganizations(
      byItem: SearchOrganizationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Organization, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudResourcemanagerV3.SearchOrganizationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.searchOrganizations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Organizations.getIamPolicy`
    public func getIamPolicy(
      request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1.Policy {
      try await self.inner.getIamPolicy(request: request, options: options)
    }

    /// See `Organizations.setIamPolicy`
    public func setIamPolicy(
      request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1.Policy {
      try await self.inner.setIamPolicy(request: request, options: options)
    }

    /// See `Organizations.testIamPermissions`
    public func testIamPermissions(
      request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1.TestIamPermissionsResponse {
      try await self.inner.testIamPermissions(request: request, options: options)
    }

    /// See `Organizations.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension Organizations {
  public func getOrganization(request: GetOrganizationRequest) async throws
    -> GoogleCloudResourcemanagerV3.Organization
  {
    try await self.getOrganization(request: request, options: .init())
  }

  public func getOrganization(
    request: GetOrganizationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourcemanagerV3.Organization {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchOrganizations(request: SearchOrganizationsRequest) async throws
    -> GoogleCloudResourcemanagerV3.SearchOrganizationsResponse
  {
    try await self.searchOrganizations(request: request, options: .init())
  }

  public func searchOrganizations(
    request: SearchOrganizationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourcemanagerV3.SearchOrganizationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchOrganizations(
    byItem: SearchOrganizationsRequest
  ) throws -> any AsyncSequence<Organization, Swift.Error> {
    try self.searchOrganizations(byItem: byItem, options: .init())
  }

  public func searchOrganizations(
    byItem: SearchOrganizationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Organization, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudResourcemanagerV3.SearchOrganizationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getIamPolicy(request: GetIamPolicyRequest) async throws -> GoogleIamV1.Policy {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: SetIamPolicyRequest) async throws -> GoogleIamV1.Policy {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: TestIamPermissionsRequest) async throws
    -> GoogleIamV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
