// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A project is a high-level Google Cloud entity. It is a
/// container for ACLs, APIs, App Engine Apps, VMs, and other
/// Google Cloud Platform resources.
public struct Project: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The unique resource name of the project. It is an int64
  /// generated number prefixed by "projects/".
  ///
  /// Example: `projects/415104041262`
  public var name: Swift.String = Swift.String()

  /// Optional. A reference to a parent Resource. eg., `organizations/123` or
  /// `folders/876`.
  public var parent: Swift.String = Swift.String()

  /// Immutable. The unique, user-assigned id of the project.
  /// It must be 6 to 30 lowercase ASCII letters, digits, or hyphens.
  /// It must start with a letter.
  /// Trailing hyphens are prohibited.
  ///
  /// Example: `tokyo-rain-123`
  public var projectId: Swift.String = Swift.String()

  /// Output only. The project lifecycle state.
  public var state: Project.State = Project.State()

  /// Optional. A user-assigned display name of the project.
  /// When present it must be between 4 to 30 characters.
  /// Allowed characters are: lowercase and uppercase letters, numbers,
  /// hyphen, single-quote, double-quote, space, and exclamation point.
  ///
  /// Example: `My Project`
  public var displayName: Swift.String = Swift.String()

  /// Output only. Creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The most recent time this resource was modified.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which this resource was requested for deletion.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. A checksum computed by the server based on the current value
  /// of the Project resource. This may be sent on update and delete requests to
  /// ensure the client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. The labels associated with this project.
  ///
  /// Label keys must be between 1 and 63 characters long and must conform
  /// to the following regular expression: \[a-z\](\[-a-z0-9\]*\[a-z0-9\])?.
  ///
  /// Label values must be between 0 and 63 characters long and must conform
  /// to the regular expression (\[a-z\](\[-a-z0-9\]*\[a-z0-9\])?)?.
  ///
  /// No more than 64 labels can be associated with a given resource.
  ///
  /// Clients should store labels in a representation such as JSON that does not
  /// depend on specific characters being disallowed.
  ///
  /// Example: `"myBusinessDimension" : "businessValue"`
  public var labels: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `Project`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Project().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Project lifecycle states.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.  This is only used/useful for distinguishing
    /// unset values.
    case unspecified
    /// The normal and active state.
    case active
    /// The project has been marked for deletion by the user
    /// (by invoking
    /// [DeleteProject][google.cloud.resourcemanager.v3.Projects.DeleteProject])
    /// or by the system (Google Cloud Platform).
    /// This can generally be reversed by invoking [UndeleteProject]
    /// [google.cloud.resourcemanager.v3.Projects.UndeleteProject].
    ///
    /// [google.cloud.resourcemanager.v3.Projects.DeleteProject]: <doc:ProjectsClient/deleteProject(request:options:)>
    case deleteRequested
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .deleteRequested: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .deleteRequested: return "DELETE_REQUESTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "DELETE_REQUESTED": self = .deleteRequested
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .deleteRequested
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .deleteRequested: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.Project"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
