// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// The response message for searching folders.
public struct SearchFoldersResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// A possibly paginated folder search results.
  /// the specified parent resource.
  public var folders: [Folder]

  /// A pagination token returned from a previous call to `SearchFolders`
  /// that indicates from where searching should continue.
  public var nextPageToken: Swift.String

  /// Initialize a new instance of `SearchFoldersResponse`.
  public init(
    folders: [Folder] = [],
    nextPageToken: Swift.String = Swift.String(),
  ) {
    self.folders = folders
    self.nextPageToken = nextPageToken
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.SearchFoldersResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [Folder] {
    return self.folders
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
