// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The request sent to the `SearchOrganizations` method.
public struct SearchOrganizationsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The maximum number of organizations to return in the response.
  /// The server can return fewer organizations than requested. If unspecified,
  /// server picks an appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A pagination token returned from a previous call to
  /// `SearchOrganizations` that indicates from where listing should continue.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. An optional query string used to filter the Organizations to
  /// return in the response. Query rules are case-insensitive.
  ///
  ///
  /// ```
  /// | Field            | Description                                |
  /// |------------------|--------------------------------------------|
  /// | directoryCustomerId, owner.directoryCustomerId | Filters by directory
  /// customer id. |
  /// | domain           | Filters by domain.                         |
  /// ```
  ///
  /// Organizations may be queried by `directoryCustomerId` or by
  /// `domain`, where the domain is a G Suite domain, for example:
  ///
  /// * Query `directorycustomerid:123456789` returns Organization
  /// resources with `owner.directory_customer_id` equal to `123456789`.
  /// * Query `domain:google.com` returns Organization resources corresponding
  /// to the domain `google.com`.
  public var query: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SearchOrganizationsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchOrganizationsRequest().with { $0.pageSize = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let query = CodingKeys(stringValue: "query")

    static let _knownKeys: Set<Swift.String> = [
      "pageSize",
      "pageToken",
      "query",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .query) {
      self.query = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.query, forKey: .query)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.SearchOrganizationsRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
