// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The request sent to the
/// [SearchProjects][google.cloud.resourcemanager.v3.Projects.SearchProjects]
/// method.
///
/// [google.cloud.resourcemanager.v3.Projects.SearchProjects]: <doc:ProjectsClient/searchProjects(request:options:)>
public struct SearchProjectsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. A query string for searching for projects that the caller has
  /// `resourcemanager.projects.get` permission to. If multiple fields are
  /// included in the query, then it will return results that match any of the
  /// fields. Some eligible fields are:
  ///
  /// - **`displayName`, `name`**: Filters by displayName.
  /// - **`parent`**: Project's parent (for example: `folders/123`,
  /// `organizations/*`). Prefer `parent` field over `parent.type` and
  /// `parent.id`.
  /// - **`parent.type`**: Parent's type: `folder` or `organization`.
  /// - **`parent.id`**: Parent's id number (for example: `123`).
  /// - **`id`, `projectId`**: Filters by projectId.
  /// - **`state`, `lifecycleState`**: Filters by state.
  /// - **`labels`**: Filters by label name or value.
  /// - **`labels.<key>` (where `<key>` is the name of a label)**: Filters by label
  /// name.
  ///
  /// Search expressions are case insensitive.
  ///
  /// Some examples queries:
  ///
  ///
  /// - **`name:how*`**: The project's name starts with "how".
  /// - **`name:Howl`**: The project's name is `Howl` or `howl`.
  /// - **`name:HOWL`**: Equivalent to above.
  /// - **`NAME:howl`**: Equivalent to above.
  /// - **`labels.color:*`**: The project has the label `color`.
  /// - **`labels.color:red`**:  The project's label `color` has the value `red`.
  /// - **`labels.color:red labels.size:big`**: The project's label `color` has
  /// the value `red` or its label `size` has the value `big`.
  ///
  /// If no query is specified, the call will return projects for which the user
  /// has the `resourcemanager.projects.get` permission.
  public var query: Swift.String = Swift.String()

  /// Optional. A pagination token returned from a previous call to
  /// [ListProjects] [google.cloud.resourcemanager.v3.Projects.ListProjects] that
  /// indicates from where listing should continue.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The maximum number of projects to return in the response.
  /// The server can return fewer projects than requested.
  /// If unspecified, server picks an appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `SearchProjectsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchProjectsRequest().with { $0.query = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.SearchProjectsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
