// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The request message for searching folders.
public struct SearchFoldersRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The maximum number of folders to return in the response. The
  /// server can return fewer folders than requested. If unspecified, server
  /// picks an appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A pagination token returned from a previous call to
  /// `SearchFolders` that indicates from where search should continue.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Search criteria used to select the folders to return.
  /// If no search criteria is specified then all accessible folders will be
  /// returned.
  ///
  /// Query expressions can be used to restrict results based upon displayName,
  /// state and parent, where the operators `=` (`:`) `NOT`, `AND` and `OR`
  /// can be used along with the suffix wildcard symbol `*`.
  ///
  /// The `displayName` field in a query expression should use escaped quotes
  /// for values that include whitespace to prevent unexpected behavior.
  ///
  /// ```
  /// | Field                   | Description                            |
  /// |-------------------------|----------------------------------------|
  /// | displayName             | Filters by displayName.                |
  /// | parent                  | Filters by parent (for example: folders/123). |
  /// | state, lifecycleState   | Filters by state.                      |
  /// ```
  ///
  /// Some example queries are:
  ///
  /// * Query `displayName=Test*` returns Folder resources whose display name
  /// starts with "Test".
  /// * Query `state=ACTIVE` returns Folder resources with
  /// `state` set to `ACTIVE`.
  /// * Query `parent=folders/123` returns Folder resources that have
  /// `folders/123` as a parent resource.
  /// * Query `parent=folders/123 AND state=ACTIVE` returns active
  /// Folder resources that have `folders/123` as a parent resource.
  /// * Query `displayName=\\"Test String\\"` returns Folder resources with
  /// display names that include both "Test" and "String".
  public var query: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SearchFoldersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchFoldersRequest().with { $0.pageSize = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let query = CodingKeys(stringValue: "query")

    static let _knownKeys: Set<Swift.String> = [
      "pageSize",
      "pageToken",
      "query",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .query) {
      self.query = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.query, forKey: .query)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.SearchFoldersRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
