// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Allow users to create and manage TagBindings between TagValues and
/// different Google Cloud resources throughout the GCP resource hierarchy.
///
/// @Snippet(path: "TagBindingsQuickstart")
public final class TagBindingsClient: Clients.TagBindingsProtocol, Sendable {
  let inner: any Clients.TagBindingsStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `TagBindingsClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.TagBindingsStub = try Clients.TagBindingsTransport(options)
    inner = Clients.TagBindingsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TagBindingsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists the TagBindings for the given Google Cloud resource, as specified
  /// with `parent`.
  ///
  /// NOTE: The `parent` field is expected to be a full resource name:
  /// https://cloud.google.com/apis/design/resource_names#full_resource_name
  ///
  /// @Snippet(path: "TagBindings_ListTagBindings")
  public func listTagBindings(
    request: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourceManagerV3.ListTagBindingsResponse {
    try await self.inner.listTagBindings(request: request, options: options)
  }

  /// Lists the TagBindings for the given Google Cloud resource, as specified
  /// with `parent`.
  ///
  /// NOTE: The `parent` field is expected to be a full resource name:
  /// https://cloud.google.com/apis/design/resource_names#full_resource_name
  ///
  /// @Snippet(path: "TagBindings_ListTagBindings")
  public func listTagBindings(
    byItem: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TagBinding, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudResourceManagerV3.ListTagBindingsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTagBindings(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates a TagBinding between a TagValue and a Google Cloud resource.
  ///
  /// @Snippet(path: "TagBindings_CreateTagBinding")
  public func createTagBinding(
    request: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createTagBinding(request: request, options: options)
  }

  /// Creates a TagBinding between a TagValue and a Google Cloud resource.
  ///
  /// @Snippet(path: "TagBindings_CreateTagBinding")
  public func createTagBinding(
    withPolling: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TagBinding> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<TagBinding>.State in
      return try op._extractStatus(TagBinding.self)
    }
    let rawOp = try await self.createTagBinding(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<TagBinding>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a TagBinding.
  ///
  /// @Snippet(path: "TagBindings_DeleteTagBinding")
  public func deleteTagBinding(
    request: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteTagBinding(request: request, options: options)
  }

  /// Deletes a TagBinding.
  ///
  /// @Snippet(path: "TagBindings_DeleteTagBinding")
  public func deleteTagBinding(
    withPolling: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteTagBinding(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Return a list of effective tags for the given Google Cloud resource, as
  /// specified in `parent`.
  ///
  /// @Snippet(path: "TagBindings_ListEffectiveTags")
  public func listEffectiveTags(
    request: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourceManagerV3.ListEffectiveTagsResponse {
    try await self.inner.listEffectiveTags(request: request, options: options)
  }

  /// Return a list of effective tags for the given Google Cloud resource, as
  /// specified in `parent`.
  ///
  /// @Snippet(path: "TagBindings_ListEffectiveTags")
  public func listEffectiveTags(
    byItem: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EffectiveTag, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudResourceManagerV3.ListEffectiveTagsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listEffectiveTags(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TagBindings_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TagBindingsClient`.
  ///
  /// To mock `TagBindingsClient` change your functions to receive
  /// `some TagBindingsProtocol` or `any TagBindingsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TagBindingsProtocol {
    /// See `TagBindingsClient.listTagBindings`.
    func listTagBindings(request: ListTagBindingsRequest) async throws
      -> GoogleCloudResourceManagerV3.ListTagBindingsResponse

    /// See `TagBindingsClient.listTagBindings`.
    func listTagBindings(
      byItem: ListTagBindingsRequest
    ) throws -> any AsyncSequence<TagBinding, Swift.Error>

    /// See `TagBindingsClient.listTagBindings`.
    func listTagBindings(
      parent: Swift.String,
    ) throws -> any AsyncSequence<TagBinding, Swift.Error>

    /// See `TagBindingsClient.createTagBinding`.
    func createTagBinding(request: CreateTagBindingRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `TagBindingsClient.createTagBinding`.
    func createTagBinding(withPolling: CreateTagBindingRequest) async throws -> any GoogleCloudGax
      .PollableOperation<TagBinding>

    /// See `TagBindingsClient.createTagBinding`.
    func createTagBinding(
      tagBinding: TagBinding?,
    ) async throws -> any GoogleCloudGax.PollableOperation<TagBinding>

    /// See `TagBindingsClient.deleteTagBinding`.
    func deleteTagBinding(request: DeleteTagBindingRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `TagBindingsClient.deleteTagBinding`.
    func deleteTagBinding(withPolling: DeleteTagBindingRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `TagBindingsClient.deleteTagBinding`.
    func deleteTagBinding(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `TagBindingsClient.listEffectiveTags`.
    func listEffectiveTags(request: ListEffectiveTagsRequest) async throws
      -> GoogleCloudResourceManagerV3.ListEffectiveTagsResponse

    /// See `TagBindingsClient.listEffectiveTags`.
    func listEffectiveTags(
      byItem: ListEffectiveTagsRequest
    ) throws -> any AsyncSequence<EffectiveTag, Swift.Error>

    /// See `TagBindingsClient.listEffectiveTags`.
    func listEffectiveTags(
      parent: Swift.String,
    ) throws -> any AsyncSequence<EffectiveTag, Swift.Error>

    /// See `TagBindingsClient.listTagBindings`.
    func listTagBindings(
      request: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourceManagerV3.ListTagBindingsResponse

    /// See `TagBindingsClient.listTagBindings`.
    func listTagBindings(
      byItem: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TagBinding, Swift.Error>

    /// See `TagBindingsClient.createTagBinding`.
    func createTagBinding(
      request: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TagBindingsClient.createTagBinding`.
    func createTagBinding(
      withPolling: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<TagBinding>

    /// See `TagBindingsClient.deleteTagBinding`.
    func deleteTagBinding(
      request: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TagBindingsClient.deleteTagBinding`.
    func deleteTagBinding(
      withPolling: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `TagBindingsClient.listEffectiveTags`.
    func listEffectiveTags(
      request: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourceManagerV3.ListEffectiveTagsResponse

    /// See `TagBindingsClient.listEffectiveTags`.
    func listEffectiveTags(
      byItem: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<EffectiveTag, Swift.Error>
  }
}

// Default implementations
extension Clients.TagBindingsProtocol {
  public func listTagBindings(request: ListTagBindingsRequest) async throws
    -> GoogleCloudResourceManagerV3.ListTagBindingsResponse
  {
    try await self.listTagBindings(request: request, options: .init())
  }

  public func listTagBindings(
    request: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourceManagerV3.ListTagBindingsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTagBindings(
    byItem: ListTagBindingsRequest
  ) throws -> any AsyncSequence<TagBinding, Swift.Error> {
    try self.listTagBindings(byItem: byItem, options: .init())
  }

  public func listTagBindings(
    byItem: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TagBinding, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudResourceManagerV3.ListTagBindingsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTagBindings(
    parent: Swift.String,
  ) throws -> any AsyncSequence<TagBinding, Swift.Error> {
    let request = ListTagBindingsRequest().with {
      $0.parent = parent
    }
    return try self.listTagBindings(byItem: request)
  }

  public func createTagBinding(request: CreateTagBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createTagBinding(request: request, options: .init())
  }

  public func createTagBinding(
    request: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createTagBinding(withPolling: CreateTagBindingRequest) async throws
    -> any GoogleCloudGax.PollableOperation<TagBinding>
  {
    try await self.createTagBinding(withPolling: withPolling, options: .init())
  }

  public func createTagBinding(
    withPolling: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TagBinding> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<TagBinding>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createTagBinding(
    tagBinding: TagBinding?,
  ) async throws -> any GoogleCloudGax.PollableOperation<TagBinding> {
    let request = CreateTagBindingRequest().with {
      $0.tagBinding = tagBinding
    }
    return try await self.createTagBinding(withPolling: request)
  }

  public func deleteTagBinding(request: DeleteTagBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteTagBinding(request: request, options: .init())
  }

  public func deleteTagBinding(
    request: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteTagBinding(withPolling: DeleteTagBindingRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteTagBinding(withPolling: withPolling, options: .init())
  }

  public func deleteTagBinding(
    withPolling: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteTagBinding(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteTagBindingRequest().with {
      $0.name = name
    }
    return try await self.deleteTagBinding(withPolling: request)
  }

  public func listEffectiveTags(request: ListEffectiveTagsRequest) async throws
    -> GoogleCloudResourceManagerV3.ListEffectiveTagsResponse
  {
    try await self.listEffectiveTags(request: request, options: .init())
  }

  public func listEffectiveTags(
    request: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourceManagerV3.ListEffectiveTagsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEffectiveTags(
    byItem: ListEffectiveTagsRequest
  ) throws -> any AsyncSequence<EffectiveTag, Swift.Error> {
    try self.listEffectiveTags(byItem: byItem, options: .init())
  }

  public func listEffectiveTags(
    byItem: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EffectiveTag, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudResourceManagerV3.ListEffectiveTagsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEffectiveTags(
    parent: Swift.String,
  ) throws -> any AsyncSequence<EffectiveTag, Swift.Error> {
    let request = ListEffectiveTagsRequest().with {
      $0.parent = parent
    }
    return try self.listEffectiveTags(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
