// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import Logging

/// Allow users to create and manage TagBindings between TagValues and
/// different Google Cloud resources throughout the GCP resource hierarchy.
///
/// @Snippet(path: "TagBindingsQuickstart")
public protocol TagBindings {
  /// Lists the TagBindings for the given Google Cloud resource, as specified
  /// with `parent`.
  ///
  /// NOTE: The `parent` field is expected to be a full resource name:
  /// https://cloud.google.com/apis/design/resource_names#full_resource_name
  ///
  /// @Snippet(path: "TagBindings_ListTagBindings")
  func listTagBindings(request: ListTagBindingsRequest) async throws
    -> GoogleCloudResourcemanagerV3.ListTagBindingsResponse

  /// Lists the TagBindings for the given Google Cloud resource, as specified
  /// with `parent`.
  ///
  /// NOTE: The `parent` field is expected to be a full resource name:
  /// https://cloud.google.com/apis/design/resource_names#full_resource_name
  func listTagBindings(
    byItem: ListTagBindingsRequest
  ) throws -> any AsyncSequence<TagBinding, Swift.Error>

  /// Creates a TagBinding between a TagValue and a Google Cloud resource.
  ///
  /// @Snippet(path: "TagBindings_CreateTagBinding")
  func createTagBinding(request: CreateTagBindingRequest) async throws
    -> GoogleLongrunning.Operation

  /// Creates a TagBinding between a TagValue and a Google Cloud resource.
  func createTagBinding(withPolling: CreateTagBindingRequest) async throws -> any GoogleCloudGax
    .PollableOperation<TagBinding>

  /// Deletes a TagBinding.
  ///
  /// @Snippet(path: "TagBindings_DeleteTagBinding")
  func deleteTagBinding(request: DeleteTagBindingRequest) async throws
    -> GoogleLongrunning.Operation

  /// Deletes a TagBinding.
  func deleteTagBinding(withPolling: DeleteTagBindingRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>

  /// Return a list of effective tags for the given Google Cloud resource, as
  /// specified in `parent`.
  ///
  /// @Snippet(path: "TagBindings_ListEffectiveTags")
  func listEffectiveTags(request: ListEffectiveTagsRequest) async throws
    -> GoogleCloudResourcemanagerV3.ListEffectiveTagsResponse

  /// Return a list of effective tags for the given Google Cloud resource, as
  /// specified in `parent`.
  func listEffectiveTags(
    byItem: ListEffectiveTagsRequest
  ) throws -> any AsyncSequence<EffectiveTag, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "TagBindings_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Lists the TagBindings for the given Google Cloud resource, as specified
  /// with `parent`.
  ///
  /// NOTE: The `parent` field is expected to be a full resource name:
  /// https://cloud.google.com/apis/design/resource_names#full_resource_name
  ///
  /// @Snippet(path: "TagBindings_ListTagBindings")
  func listTagBindings(
    request: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourcemanagerV3.ListTagBindingsResponse

  /// Lists the TagBindings for the given Google Cloud resource, as specified
  /// with `parent`.
  ///
  /// NOTE: The `parent` field is expected to be a full resource name:
  /// https://cloud.google.com/apis/design/resource_names#full_resource_name
  func listTagBindings(
    byItem: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TagBinding, Swift.Error>

  /// Creates a TagBinding between a TagValue and a Google Cloud resource.
  ///
  /// @Snippet(path: "TagBindings_CreateTagBinding")
  func createTagBinding(
    request: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Creates a TagBinding between a TagValue and a Google Cloud resource.
  func createTagBinding(
    withPolling: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TagBinding>

  /// Deletes a TagBinding.
  ///
  /// @Snippet(path: "TagBindings_DeleteTagBinding")
  func deleteTagBinding(
    request: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Deletes a TagBinding.
  func deleteTagBinding(
    withPolling: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void>

  /// Return a list of effective tags for the given Google Cloud resource, as
  /// specified in `parent`.
  ///
  /// @Snippet(path: "TagBindings_ListEffectiveTags")
  func listEffectiveTags(
    request: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourcemanagerV3.ListEffectiveTagsResponse

  /// Return a list of effective tags for the given Google Cloud resource, as
  /// specified in `parent`.
  func listEffectiveTags(
    byItem: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EffectiveTag, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "TagBindings_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation
}

extension Clients {
  /// The recommended implementation for ``TagBindings``.
  public class TagBindingsClient: TagBindings {
    let inner: any TagBindingsStub

    /// Creates a new `TagBindingsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any TagBindingsStub = try TagBindingsTransport(options)
      inner = TagBindingsRetry(inner, options: options)
      if let logger = options.logger {
        inner = TagBindingsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `TagBindings.listTagBindings`
    public func listTagBindings(
      request: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourcemanagerV3.ListTagBindingsResponse {
      try await self.inner.listTagBindings(request: request, options: options)
    }

    /// Lists the TagBindings for the given Google Cloud resource, as specified
    /// with `parent`.
    ///
    /// NOTE: The `parent` field is expected to be a full resource name:
    /// https://cloud.google.com/apis/design/resource_names#full_resource_name
    public func listTagBindings(
      byItem: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TagBinding, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudResourcemanagerV3.ListTagBindingsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listTagBindings(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `TagBindings.createTagBinding`
    public func createTagBinding(
      request: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.createTagBinding(request: request, options: options)
    }

    /// Creates a TagBinding between a TagValue and a Google Cloud resource.
    public func createTagBinding(
      withPolling: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<TagBinding> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<TagBinding>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try TagBinding(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.createTagBinding(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<TagBinding>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `TagBindings.deleteTagBinding`
    public func deleteTagBinding(
      request: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deleteTagBinding(request: request, options: options)
    }

    /// Deletes a TagBinding.
    public func deleteTagBinding(
      withPolling: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Void>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response:
          return .init(done: true, result: .success(()))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.deleteTagBinding(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `TagBindings.listEffectiveTags`
    public func listEffectiveTags(
      request: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourcemanagerV3.ListEffectiveTagsResponse {
      try await self.inner.listEffectiveTags(request: request, options: options)
    }

    /// Return a list of effective tags for the given Google Cloud resource, as
    /// specified in `parent`.
    public func listEffectiveTags(
      byItem: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<EffectiveTag, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudResourcemanagerV3.ListEffectiveTagsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listEffectiveTags(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `TagBindings.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension TagBindings {
  public func listTagBindings(request: ListTagBindingsRequest) async throws
    -> GoogleCloudResourcemanagerV3.ListTagBindingsResponse
  {
    try await self.listTagBindings(request: request, options: .init())
  }

  public func listTagBindings(
    request: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourcemanagerV3.ListTagBindingsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTagBindings(
    byItem: ListTagBindingsRequest
  ) throws -> any AsyncSequence<TagBinding, Swift.Error> {
    try self.listTagBindings(byItem: byItem, options: .init())
  }

  public func listTagBindings(
    byItem: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TagBinding, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudResourcemanagerV3.ListTagBindingsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func createTagBinding(request: CreateTagBindingRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createTagBinding(request: request, options: .init())
  }

  public func createTagBinding(
    request: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createTagBinding(withPolling: CreateTagBindingRequest) async throws
    -> any GoogleCloudGax.PollableOperation<TagBinding>
  {
    try await self.createTagBinding(withPolling: withPolling, options: .init())
  }

  public func createTagBinding(
    withPolling: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TagBinding> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<TagBinding>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteTagBinding(request: DeleteTagBindingRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteTagBinding(request: request, options: .init())
  }

  public func deleteTagBinding(
    request: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteTagBinding(withPolling: DeleteTagBindingRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Void>
  {
    try await self.deleteTagBinding(withPolling: withPolling, options: .init())
  }

  public func deleteTagBinding(
    withPolling: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listEffectiveTags(request: ListEffectiveTagsRequest) async throws
    -> GoogleCloudResourcemanagerV3.ListEffectiveTagsResponse
  {
    try await self.listEffectiveTags(request: request, options: .init())
  }

  public func listEffectiveTags(
    request: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourcemanagerV3.ListEffectiveTagsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEffectiveTags(
    byItem: ListEffectiveTagsRequest
  ) throws -> any AsyncSequence<EffectiveTag, Swift.Error> {
    try self.listEffectiveTags(byItem: byItem, options: .init())
  }

  public func listEffectiveTags(
    byItem: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EffectiveTag, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudResourcemanagerV3.ListEffectiveTagsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
