// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class TagBindingsLogging: TagBindingsStub {
    let inner: any TagBindingsStub
    let logger: Logger

    public init(_ inner: any TagBindingsStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-resourcemanager-v3"
      logger[metadataKey: "gcp.client.service"] = "cloudresourcemanager"
      logger[metadataKey: "gcp.experimental.swift.client"] = "TagBindings"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listTagBindings(
      request: ListTagBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourceManagerV3.ListTagBindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTagBindings",
        action: {
          (r: ListTagBindingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudResourceManagerV3.ListTagBindingsResponse
          in
          return try await self.inner.listTagBindings(request: r, options: o)
        })
    }

    public func createTagBinding(
      request: CreateTagBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTagBinding",
        action: {
          (r: CreateTagBindingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createTagBinding(request: r, options: o)
        })
    }

    public func deleteTagBinding(
      request: DeleteTagBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTagBinding",
        action: {
          (r: DeleteTagBindingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteTagBinding(request: r, options: o)
        })
    }

    public func listEffectiveTags(
      request: ListEffectiveTagsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourceManagerV3.ListEffectiveTagsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEffectiveTags",
        action: {
          (r: ListEffectiveTagsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudResourceManagerV3.ListEffectiveTagsResponse
          in
          return try await self.inner.listEffectiveTags(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
