// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A TagHold represents the use of a TagValue that is not captured by
/// TagBindings. If a TagValue has any TagHolds, deletion will be blocked.
/// This resource is intended to be created in the same cloud location as the
/// `holder`.
public struct TagHold: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of a TagHold. This is a String of the form:
  /// `tagValues/{tag-value-id}/tagHolds/{tag-hold-id}`
  /// (e.g. `tagValues/123/tagHolds/456`). This resource name is generated by
  /// the server.
  public var name: Swift.String = Swift.String()

  /// Required. The name of the resource where the TagValue is being used. Must
  /// be less than 200 characters. E.g.
  /// `//compute.googleapis.com/compute/projects/myproject/regions/us-east-1/instanceGroupManagers/instance-group`
  public var holder: Swift.String = Swift.String()

  /// Optional. An optional string representing the origin of this request. This
  /// field should include human-understandable information to distinguish
  /// origins from each other. Must be less than 200 characters. E.g.
  /// `migs-35678234`
  public var origin: Swift.String = Swift.String()

  /// Optional. A URL where an end user can learn more about removing this hold.
  /// E.g.
  /// `https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing`
  public var helpLink: Swift.String = Swift.String()

  /// Output only. The time this TagHold was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TagHold`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TagHold().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let holder = CodingKeys(stringValue: "holder")
    static let origin = CodingKeys(stringValue: "origin")
    static let helpLink = CodingKeys(stringValue: "helpLink")
    static let createTime = CodingKeys(stringValue: "createTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "holder",
      "origin",
      "helpLink",
      "createTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .holder) {
      self.holder = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .origin) {
      self.origin = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .helpLink) {
      self.helpLink = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.holder, forKey: .holder)
    try container.encode(self.origin, forKey: .origin)
    try container.encode(self.helpLink, forKey: .helpLink)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.TagHold"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
