// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Allow users to create and manage tag keys.
///
/// @Snippet(path: "TagKeysQuickstart")
public final class TagKeysClient: Clients.TagKeysProtocol, Sendable {
  let inner: any Clients.TagKeysStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `TagKeysClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.TagKeysStub = try Clients.TagKeysTransport(options)
    inner = Clients.TagKeysRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TagKeysLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists all TagKeys for a parent resource.
  ///
  /// @Snippet(path: "TagKeys_ListTagKeys")
  public func listTagKeys(
    request: ListTagKeysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourceManagerV3.ListTagKeysResponse {
    try await self.inner.listTagKeys(request: request, options: options)
  }

  /// Lists all TagKeys for a parent resource.
  ///
  /// @Snippet(path: "TagKeys_ListTagKeys")
  public func listTagKeys(
    byItem: ListTagKeysRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TagKey, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudResourceManagerV3.ListTagKeysResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTagKeys(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves a TagKey. This method will return `PERMISSION_DENIED` if the
  /// key does not exist or the user does not have permission to view it.
  ///
  /// @Snippet(path: "TagKeys_GetTagKey")
  public func getTagKey(
    request: GetTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourceManagerV3.TagKey {
    try await self.inner.getTagKey(request: request, options: options)
  }

  /// Retrieves a TagKey by its namespaced name.
  /// This method will return `PERMISSION_DENIED` if the key does not exist
  /// or the user does not have permission to view it.
  ///
  /// @Snippet(path: "TagKeys_GetNamespacedTagKey")
  public func getNamespacedTagKey(
    request: GetNamespacedTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourceManagerV3.TagKey {
    try await self.inner.getNamespacedTagKey(request: request, options: options)
  }

  /// Creates a new TagKey. If another request with the same parameters is
  /// sent while the original request is in process, the second request
  /// will receive an error. A maximum of 1000 TagKeys can exist under a parent
  /// at any given time.
  ///
  /// @Snippet(path: "TagKeys_CreateTagKey")
  public func createTagKey(
    request: CreateTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createTagKey(request: request, options: options)
  }

  /// Creates a new TagKey. If another request with the same parameters is
  /// sent while the original request is in process, the second request
  /// will receive an error. A maximum of 1000 TagKeys can exist under a parent
  /// at any given time.
  ///
  /// @Snippet(path: "TagKeys_CreateTagKey")
  public func createTagKey(
    withPolling: CreateTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TagKey> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<TagKey>.State in
      return try op._extractStatus(TagKey.self)
    }
    let rawOp = try await self.createTagKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<TagKey>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the attributes of the TagKey resource.
  ///
  /// @Snippet(path: "TagKeys_UpdateTagKey")
  public func updateTagKey(
    request: UpdateTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateTagKey(request: request, options: options)
  }

  /// Updates the attributes of the TagKey resource.
  ///
  /// @Snippet(path: "TagKeys_UpdateTagKey")
  public func updateTagKey(
    withPolling: UpdateTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TagKey> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<TagKey>.State in
      return try op._extractStatus(TagKey.self)
    }
    let rawOp = try await self.updateTagKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<TagKey>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a TagKey. The TagKey cannot be deleted if it has any child
  /// TagValues.
  ///
  /// @Snippet(path: "TagKeys_DeleteTagKey")
  public func deleteTagKey(
    request: DeleteTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteTagKey(request: request, options: options)
  }

  /// Deletes a TagKey. The TagKey cannot be deleted if it has any child
  /// TagValues.
  ///
  /// @Snippet(path: "TagKeys_DeleteTagKey")
  public func deleteTagKey(
    withPolling: DeleteTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TagKey> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<TagKey>.State in
      return try op._extractStatus(TagKey.self)
    }
    let rawOp = try await self.deleteTagKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<TagKey>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets the access control policy for a TagKey. The returned policy may be
  /// empty if no such policy or resource exists. The `resource` field should
  /// be the TagKey's resource name. For example, "tagKeys/1234".
  /// The caller must have
  /// `cloudresourcemanager.googleapis.com/tagKeys.getIamPolicy` permission on
  /// the specified TagKey.
  ///
  /// @Snippet(path: "TagKeys_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Sets the access control policy on a TagKey, replacing any existing
  /// policy. The `resource` field should be the TagKey's resource name.
  /// For example, "tagKeys/1234".
  /// The caller must have `resourcemanager.tagKeys.setIamPolicy` permission
  /// on the identified tagValue.
  ///
  /// @Snippet(path: "TagKeys_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified TagKey.
  /// The `resource` field should be the TagKey's resource name.
  /// For example, "tagKeys/1234".
  ///
  /// There are no permissions required for making this API call.
  ///
  /// @Snippet(path: "TagKeys_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TagKeys_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TagKeysClient`.
  ///
  /// To mock `TagKeysClient` change your functions to receive
  /// `some TagKeysProtocol` or `any TagKeysProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TagKeysProtocol {
    /// See `TagKeysClient.listTagKeys`.
    func listTagKeys(request: ListTagKeysRequest) async throws
      -> GoogleCloudResourceManagerV3.ListTagKeysResponse

    /// See `TagKeysClient.listTagKeys`.
    func listTagKeys(
      byItem: ListTagKeysRequest
    ) throws -> any AsyncSequence<TagKey, Swift.Error>

    /// See `TagKeysClient.listTagKeys`.
    func listTagKeys(
      parent: Swift.String,
    ) throws -> any AsyncSequence<TagKey, Swift.Error>

    /// See `TagKeysClient.getTagKey`.
    func getTagKey(request: GetTagKeyRequest) async throws -> GoogleCloudResourceManagerV3.TagKey

    /// See `TagKeysClient.getTagKey`.
    func getTagKey(
      name: Swift.String,
    ) async throws -> GoogleCloudResourceManagerV3.TagKey

    /// See `TagKeysClient.getNamespacedTagKey`.
    func getNamespacedTagKey(request: GetNamespacedTagKeyRequest) async throws
      -> GoogleCloudResourceManagerV3.TagKey

    /// See `TagKeysClient.getNamespacedTagKey`.
    func getNamespacedTagKey(
      name: Swift.String,
    ) async throws -> GoogleCloudResourceManagerV3.TagKey

    /// See `TagKeysClient.createTagKey`.
    func createTagKey(request: CreateTagKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `TagKeysClient.createTagKey`.
    func createTagKey(withPolling: CreateTagKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<TagKey>

    /// See `TagKeysClient.createTagKey`.
    func createTagKey(
      tagKey: TagKey?,
    ) async throws -> any GoogleCloudGax.PollableOperation<TagKey>

    /// See `TagKeysClient.updateTagKey`.
    func updateTagKey(request: UpdateTagKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `TagKeysClient.updateTagKey`.
    func updateTagKey(withPolling: UpdateTagKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<TagKey>

    /// See `TagKeysClient.updateTagKey`.
    func updateTagKey(
      tagKey: TagKey?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<TagKey>

    /// See `TagKeysClient.deleteTagKey`.
    func deleteTagKey(request: DeleteTagKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `TagKeysClient.deleteTagKey`.
    func deleteTagKey(withPolling: DeleteTagKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<TagKey>

    /// See `TagKeysClient.deleteTagKey`.
    func deleteTagKey(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<TagKey>

    /// See `TagKeysClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `TagKeysClient.getIamPolicy`.
    func getIamPolicy(
      resource: Swift.String,
    ) async throws -> GoogleIAMV1.Policy

    /// See `TagKeysClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `TagKeysClient.setIamPolicy`.
    func setIamPolicy(
      resource: Swift.String,
      policy: GoogleIAMV1.Policy?,
    ) async throws -> GoogleIAMV1.Policy

    /// See `TagKeysClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `TagKeysClient.testIamPermissions`.
    func testIamPermissions(
      resource: Swift.String,
      permissions: [Swift.String],
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `TagKeysClient.listTagKeys`.
    func listTagKeys(
      request: ListTagKeysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourceManagerV3.ListTagKeysResponse

    /// See `TagKeysClient.listTagKeys`.
    func listTagKeys(
      byItem: ListTagKeysRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TagKey, Swift.Error>

    /// See `TagKeysClient.getTagKey`.
    func getTagKey(
      request: GetTagKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourceManagerV3.TagKey

    /// See `TagKeysClient.getNamespacedTagKey`.
    func getNamespacedTagKey(
      request: GetNamespacedTagKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudResourceManagerV3.TagKey

    /// See `TagKeysClient.createTagKey`.
    func createTagKey(
      request: CreateTagKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TagKeysClient.createTagKey`.
    func createTagKey(
      withPolling: CreateTagKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<TagKey>

    /// See `TagKeysClient.updateTagKey`.
    func updateTagKey(
      request: UpdateTagKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TagKeysClient.updateTagKey`.
    func updateTagKey(
      withPolling: UpdateTagKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<TagKey>

    /// See `TagKeysClient.deleteTagKey`.
    func deleteTagKey(
      request: DeleteTagKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TagKeysClient.deleteTagKey`.
    func deleteTagKey(
      withPolling: DeleteTagKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<TagKey>

    /// See `TagKeysClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `TagKeysClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `TagKeysClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse
  }
}

// Default implementations
extension Clients.TagKeysProtocol {
  public func listTagKeys(request: ListTagKeysRequest) async throws
    -> GoogleCloudResourceManagerV3.ListTagKeysResponse
  {
    try await self.listTagKeys(request: request, options: .init())
  }

  public func listTagKeys(
    request: ListTagKeysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourceManagerV3.ListTagKeysResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTagKeys(
    byItem: ListTagKeysRequest
  ) throws -> any AsyncSequence<TagKey, Swift.Error> {
    try self.listTagKeys(byItem: byItem, options: .init())
  }

  public func listTagKeys(
    byItem: ListTagKeysRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TagKey, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudResourceManagerV3.ListTagKeysResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTagKeys(
    parent: Swift.String,
  ) throws -> any AsyncSequence<TagKey, Swift.Error> {
    let request = ListTagKeysRequest().with {
      $0.parent = parent
    }
    return try self.listTagKeys(byItem: request)
  }

  public func getTagKey(request: GetTagKeyRequest) async throws
    -> GoogleCloudResourceManagerV3.TagKey
  {
    try await self.getTagKey(request: request, options: .init())
  }

  public func getTagKey(
    request: GetTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourceManagerV3.TagKey {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getTagKey(
    name: Swift.String,
  ) async throws -> GoogleCloudResourceManagerV3.TagKey {
    let request = GetTagKeyRequest().with {
      $0.name = name
    }
    return try await self.getTagKey(request: request)
  }

  public func getNamespacedTagKey(request: GetNamespacedTagKeyRequest) async throws
    -> GoogleCloudResourceManagerV3.TagKey
  {
    try await self.getNamespacedTagKey(request: request, options: .init())
  }

  public func getNamespacedTagKey(
    request: GetNamespacedTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudResourceManagerV3.TagKey {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getNamespacedTagKey(
    name: Swift.String,
  ) async throws -> GoogleCloudResourceManagerV3.TagKey {
    let request = GetNamespacedTagKeyRequest().with {
      $0.name = name
    }
    return try await self.getNamespacedTagKey(request: request)
  }

  public func createTagKey(request: CreateTagKeyRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.createTagKey(request: request, options: .init())
  }

  public func createTagKey(
    request: CreateTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createTagKey(withPolling: CreateTagKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<TagKey>
  {
    try await self.createTagKey(withPolling: withPolling, options: .init())
  }

  public func createTagKey(
    withPolling: CreateTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TagKey> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<TagKey>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createTagKey(
    tagKey: TagKey?,
  ) async throws -> any GoogleCloudGax.PollableOperation<TagKey> {
    let request = CreateTagKeyRequest().with {
      $0.tagKey = tagKey
    }
    return try await self.createTagKey(withPolling: request)
  }

  public func updateTagKey(request: UpdateTagKeyRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.updateTagKey(request: request, options: .init())
  }

  public func updateTagKey(
    request: UpdateTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateTagKey(withPolling: UpdateTagKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<TagKey>
  {
    try await self.updateTagKey(withPolling: withPolling, options: .init())
  }

  public func updateTagKey(
    withPolling: UpdateTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TagKey> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<TagKey>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateTagKey(
    tagKey: TagKey?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<TagKey> {
    let request = UpdateTagKeyRequest().with {
      $0.tagKey = tagKey
      $0.updateMask = updateMask
    }
    return try await self.updateTagKey(withPolling: request)
  }

  public func deleteTagKey(request: DeleteTagKeyRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteTagKey(request: request, options: .init())
  }

  public func deleteTagKey(
    request: DeleteTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteTagKey(withPolling: DeleteTagKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<TagKey>
  {
    try await self.deleteTagKey(withPolling: withPolling, options: .init())
  }

  public func deleteTagKey(
    withPolling: DeleteTagKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TagKey> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<TagKey>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteTagKey(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<TagKey> {
    let request = DeleteTagKeyRequest().with {
      $0.name = name
    }
    return try await self.deleteTagKey(withPolling: request)
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(
    resource: Swift.String,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.GetIamPolicyRequest().with {
      $0.resource = resource
    }
    return try await self.getIamPolicy(request: request)
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(
    resource: Swift.String,
    policy: GoogleIAMV1.Policy?,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.SetIamPolicyRequest().with {
      $0.resource = resource
      $0.policy = policy
    }
    return try await self.setIamPolicy(request: request)
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(
    resource: Swift.String,
    permissions: [Swift.String],
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    let request = GoogleIAMV1.TestIamPermissionsRequest().with {
      $0.resource = resource
      $0.permissions = permissions
    }
    return try await self.testIamPermissions(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
