// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class TagKeysLogging: TagKeysStub {
    let inner: any TagKeysStub
    let logger: Logger

    public init(_ inner: any TagKeysStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-resourcemanager-v3"
      logger[metadataKey: "gcp.client.service"] = "cloudresourcemanager"
      logger[metadataKey: "gcp.experimental.swift.client"] = "TagKeys"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listTagKeys(
      request: ListTagKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudResourceManagerV3.ListTagKeysResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTagKeys",
        action: {
          (r: ListTagKeysRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudResourceManagerV3.ListTagKeysResponse
          in
          return try await self.inner.listTagKeys(request: r, options: o)
        })
    }

    public func getTagKey(
      request: GetTagKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudResourceManagerV3.TagKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTagKey",
        action: {
          (r: GetTagKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudResourceManagerV3.TagKey
          in
          return try await self.inner.getTagKey(request: r, options: o)
        })
    }

    public func getNamespacedTagKey(
      request: GetNamespacedTagKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudResourceManagerV3.TagKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNamespacedTagKey",
        action: {
          (r: GetNamespacedTagKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudResourceManagerV3.TagKey
          in
          return try await self.inner.getNamespacedTagKey(request: r, options: o)
        })
    }

    public func createTagKey(
      request: CreateTagKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTagKey",
        action: {
          (r: CreateTagKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createTagKey(request: r, options: o)
        })
    }

    public func updateTagKey(
      request: UpdateTagKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTagKey",
        action: {
          (r: UpdateTagKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateTagKey(request: r, options: o)
        })
    }

    public func deleteTagKey(
      request: DeleteTagKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTagKey",
        action: {
          (r: DeleteTagKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteTagKey(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
