// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A TagValue is a child of a particular TagKey. This is used to group
/// cloud resources for the purpose of controlling them using policies.
public struct TagValue: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. Resource name for TagValue in the format `tagValues/456`.
  public var name: Swift.String = Swift.String()

  /// Immutable. The resource name of the new TagValue's parent TagKey.
  /// Must be of the form `tagKeys/{tag_key_id}`.
  public var parent: Swift.String = Swift.String()

  /// Required. Immutable. User-assigned short name for TagValue. The short name
  /// should be unique for TagValues within the same parent TagKey.
  ///
  /// The short name must be 63 characters or less, beginning and ending with
  /// an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_),
  /// dots (.), and alphanumerics between.
  public var shortName: Swift.String = Swift.String()

  /// Output only. The namespaced name of the TagValue. Can be in the form
  /// `{organization_id}/{tag_key_short_name}/{tag_value_short_name}` or
  /// `{project_id}/{tag_key_short_name}/{tag_value_short_name}` or
  /// `{project_number}/{tag_key_short_name}/{tag_value_short_name}`.
  public var namespacedName: Swift.String = Swift.String()

  /// Optional. User-assigned description of the TagValue.
  /// Must not exceed 256 characters.
  ///
  /// Read-write.
  public var description: Swift.String = Swift.String()

  /// Output only. Creation time.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Update time.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Entity tag which users can pass to prevent race conditions. This
  /// field is always set in server responses. See UpdateTagValueRequest for
  /// details.
  public var etag: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TagValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TagValue().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let parent = CodingKeys(stringValue: "parent")
    static let shortName = CodingKeys(stringValue: "shortName")
    static let namespacedName = CodingKeys(stringValue: "namespacedName")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "parent",
      "shortName",
      "namespacedName",
      "description",
      "createTime",
      "updateTime",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .shortName) {
      self.shortName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .namespacedName) {
      self.namespacedName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.shortName, forKey: .shortName)
    try container.encode(self.namespacedName, forKey: .namespacedName)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.TagValue"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
