// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request sent to the
/// [UpdateFolder][google.cloud.resourcemanager.v3.Folder.UpdateFolder]
/// method.
///
/// Only the `display_name` field can be changed. All other fields will be
/// ignored. Use the
/// [MoveFolder][google.cloud.resourcemanager.v3.Folders.MoveFolder] method to
/// change the `parent` field.
///
/// [google.cloud.resourcemanager.v3.Folders.MoveFolder]: <doc:Folders/moveFolder(request:)>
public struct UpdateFolderRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The new definition of the Folder. It must include the `name`
  /// field, which cannot be changed.
  public var folder: Folder? = nil

  /// Required. Fields to be updated.
  /// Only the `display_name` can be updated.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateFolderRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateFolderRequest().with { $0.folder = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.UpdateFolderRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
