// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The request message for updating a TagKey.
public struct UpdateTagKeyRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The new definition of the TagKey. Only the `description` and
  /// `etag` fields can be updated by this request. If the `etag` field is not
  /// empty, it must match the `etag` field of the existing tag key. Otherwise,
  /// `ABORTED` will be returned.
  public var tagKey: TagKey? = nil

  /// Fields to be updated. The mask may only contain `description` or
  /// `etag`. If omitted entirely, both `description` and `etag` are assumed to
  /// be significant.
  public var updateMask: GoogleCloudWKT.FieldMask? = nil

  /// Set as true to perform validations necessary for updating the resource, but
  /// not actually perform the action.
  public var validateOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateTagKeyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateTagKeyRequest().with { $0.tagKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let tagKey = CodingKeys(stringValue: "tagKey")
    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")

    static let _knownKeys: Set<Swift.String> = [
      "tagKey",
      "updateMask",
      "validateOnly",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.tagKey = try container.decodeIfPresent(TagKey.self, forKey: .tagKey)
    self.updateMask = try container.decodeIfPresent(
      GoogleCloudWKT.FieldMask.self, forKey: .updateMask)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.tagKey, forKey: .tagKey)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.UpdateTagKeyRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
