// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request sent to the
/// [UpdateProject][google.cloud.resourcemanager.v3.Projects.UpdateProject]
/// method.
///
/// Only the `display_name` and `labels` fields can be change. Use the
/// [MoveProject][google.cloud.resourcemanager.v3.Projects.MoveProject] method to
/// change the `parent` field.
///
/// [google.cloud.resourcemanager.v3.Projects.MoveProject]: <doc:Projects/moveProject(request:)>
/// [google.cloud.resourcemanager.v3.Projects.UpdateProject]: <doc:Projects/updateProject(request:)>
public struct UpdateProjectRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The new definition of the project.
  public var project: Project?

  /// Optional. An update mask to selectively update fields.
  public var updateMask: GoogleCloudWkt.FieldMask?

  /// Initialize a new instance of `UpdateProjectRequest`.
  public init(
    project: Project? = nil,
    updateMask: GoogleCloudWkt.FieldMask? = nil,
  ) {
    self.project = project
    self.updateMask = updateMask
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.resourcemanager.v3.UpdateProjectRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
